#Postgresql Devel
development:
  adapter: postgresql
  encoding: unicode
  database: cgdv_development
  pool: 5
  username: <%= ENV['PGUSER'] || Rails.application.credentials.db_username %>
  password: <%= ENV['PGPASSWORD'] || Rails.application.credentials.db_password %>
  <% if ENV['PGHOST'] %>
  host: <%= ENV['PGHOST'] %>
  <% end %>
  <% if ENV['PGPORT'] %>
  port: <%= ENV['PGPORT'] %>
  <% end %>

test:
  adapter: postgresql
  encoding: unicode
  database: cgdv_test
  pool: 5
  username: <%= ENV['PGUSER'] || Rails.application.credentials.db_username %>
  password: <%= ENV['PGPASSWORD'] || Rails.application.credentials.db_password %>
  <% if ENV['PGHOST'] %>
  host: <%= ENV['PGHOST'] %>
  <% end %>
  <% if ENV['PGPORT'] %>
  port: <%= ENV['PGPORT'] %>
  <% end %>

# Localhost
production:
  adapter: postgresql
  encoding: unicode
  database: cgdv_production
  pool: 5
  username: <%= ENV['PGUSER'] || Rails.application.credentials.db_username %>
  password: <%= ENV['PGPASSWORD'] || Rails.application.credentials.db_password %>
  <% if ENV['PGHOST'] %>
  host: <%= ENV['PGHOST'] %>
  <% end %>
  <% if ENV['PGPORT'] %>
  port: <%= ENV['PGPORT'] %>
  <% end %>
